appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Ve+b8dbaaWdSfOQzHrEGa3/jtTJgfKWn4jFsDzd+BuZxjFUbicjgVMY215+t4W7DL9Gya1+oNp12Moxosrxh0a/9tC06sLaRU2DxhLuv1K7RZ5OCxopY+a0jwepmwgI78GuNDuaswDYgzO6xtNIOdeGBX4IIC0qdrhpDnTBxwJjw4/7pLOPgkg//PwolBWii6QsFrOm86JYEawgnfIqCrEmEuGGWiZvkW4qcLmp19+8Xs3sf8djvBGHhOot0hmGJiP7TVXw3RMgQPqHpbKK7mWXKKJdPdKhdhlm00IWdVJ6JFgdH8fkpdzhirWowCzSW9YB7txlLEUJtH7vRXC5SK1TO65WmOF5b4uesINHapuyR89pOqmBmLStiZ1W28svQHgQHbSkm7Uhn89D228KWBDSOHzh4xW3or6GJ2hjvcJnPpmXtnIXYrYYa6VLMS4A2nzBHxxSH9mZkE1HkLuvcLfwgdO7RgvsgPujXCFP6Q4bwHYCKYCewiPCtEEyawyQ9iHXvAkkaOwg8pOwad9Z+m3oEiaLrIP8QcfvBQ+clehTulyzfVdzRoEKHEgbIJaj4mv9iCbi+bKvXadSg2q1Q7Z2wLOQWtqKBr9YmBMCaT5bjOloxUCvp8/6IZTsNzy6/JqA8SwOxmQ3IQo21OueLJTEIM+77M10D3US4VrMnUsk=}
bot:
  automerge: true
